[package]
name = "supervisor"
version = "0.0.1"
authors = ["Chris Williams <diosix@tuta.io>"]
license = "MIT"
edition = "2018"
publish = false

# external dependencies
[dependencies.riscv]
version = "0.6.0"
